### ISSUE TITLE
After 20min

### ISSUE THREAD

**Issue by FarmTon** [A-KTO-Tbl/Bcoin2048#1]
![imagen](https://github.com/user-attachments/assets/9de98266-71e1-428b-9ca7-7929f1272488)

**Comment by A-KTO-Tbl** [comment]
Обнови скрипт, полностью всё исправлено. И судя по всему, в твоём случае ошибки из-за неверных ссылок в конфиге

**Comment by FarmTon** [comment]
Спасибо ! работает
