### ISSUE TITLE
Бот не запускает игры

### ISSUE THREAD

**Issue by FarmTon** [A-KTO-Tbl/Bcoin2048#4]

**Comment by Imaroubat** [comment]
получи новую ссылку через /start

**Comment by FarmTon** [comment]
летаю! Спасибо

**Comment by A-KTO-Tbl** [comment]
только что проверял на разных акка, руками, и люди разные помогали проверить, сам бкоин не даёт создать новую игру, что-то с серверами ихними, скрипт здесь не причём
